version: "3.9"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    container_name: es01
    networks:
      - elastic
    ports:
      - "9200:9200"
    mem_limit: 1g
    environment:
      - discovery.type=single-node
    tty: true
    stdin_open: true

networks:
  elastic:
    external: true
    
